name: Kernel Module Build (Loganysl)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Clang from kdrag0n/proton-clang action
      uses: kdrag0n/proton-clang@v1

    - name: Build kernel module
      env:
        ARCH: arm64
        PATH: ${{ env.PROTON_CLANG }}/bin:$PATH
      run: |
        make O=out ARCH=arm64 CC=clang d8g_defconfig
        make O=out ARCH=arm64 CC=clang modules

    - uses: actions/upload-artifact@v4
      with:
        name: loganysl-module
        path: out/drivers/loganysl/loganysl.ko
