name: Kernel Module Build (Loganysl)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up Clang toolchain and build module
      env:
        ARCH: arm64
        PATH: ${{ github.workspace }}/clang/bin:$PATH
      run: |
        git clone https://github.com/kdrag0n/proton-clang --depth=1 clang
        make O=out ARCH=arm64 CC=clang d8g_defconfig
        make O=out ARCH=arm64 CC=clang modules

    - name: Upload built loganysl.ko
      uses: actions/upload-artifact@v4
      with:
        name: loganysl-module
        path: out/drivers/loganysl/loganysl.ko
