name: Kernel Module Build (Loganysl)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Clang
        uses: llvm/llvm-project@main
        with:
          llvm-version: '15.0.0'  # You can change to a stable clang version

      - name: Build kernel module
        env:
          ARCH: arm64
          PATH: /usr/bin:$PATH
        run: |
          make O=out ARCH=arm64 CC=clang d8g_defconfig
          make O=out ARCH=arm64 CC=clang modules

      - uses: actions/upload-artifact@v4
        with:
          name: loganysl-module
          path: out/drivers/loganysl/loganysl.ko
